spring:
  application:
    name: 'ms-recommendation'
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/recommendation
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8084
eureka:
  instance:
    hostname: ${vcap.application.url[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMlliseconds: 1000
management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
   enabled: true
logging:
  level:
    com:
      netflix:
        loadbalancer:
          LoadBalancerContext: DEBUG