server.port: 8101

spring:
  application.name: config-server
  cloud.config:
    server.git:
      uri: https://github.com/alejandro-du/vaadin-microservices-demo-config.git
      default-label: master
  cloud:
    config:
      server:
        git:
          clone-on-start: true
eureka:
  instance:
    hostname: ${vcap.application.url[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
